version: "3.9"
services:
  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  api:
    # build: .
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json
      # ./folder:folder -> sincronia da pasta
      # ./folder/:folder -> sincronia de arquivos dentro da pasta
      - ./dist:/app/dist
    ports:
      - 5050:5050
      - 9222:9222
    command: sh -c "npm install --only=prod && npm run debug"
    depends_on:
      mongo:
        condition: service_healthy
    links:
      - "mongo"




